name: Main
on:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Install libs
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Build Crash Handler (Windows)
        run: |
          cd crshhndlr
          haxelib run lime build windows
          cd ..

      - name: Build Main Game
        run: haxelib run lime build windows

  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libvlc-dev libvlccore-dev

      - name: Install libs
        run: |
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Fix hxCodec
        run: rm -rf ~/.haxelib/hxCodec/*/lib/vlc/lib/Linux

      - name: Build Crash Handler (Linux)
        # Note: If your engine only supports the crash handler on Windows, 
        # you may need to skip this or fix your Project.xml (see below).
        run: |
          cd crshhndlr
          haxelib run lime build linux
          cd ..

      - name: Build Main Game
        run: haxelib run lime build linux
